# Generated by Django 5.1 on 2024-08-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palabra',
            old_name='texto',
            new_name='palabra',
        ),
        migrations.AlterField(
            model_name='palabra',
            name='pista',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
