# Generated by Django 5.1 on 2024-08-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_rename_texto_palabra_palabra_alter_palabra_pista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='palabra',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='pista',
            field=models.CharField(max_length=200),
        ),
    ]
